name: sam-batcher-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - matplotlib
  - pip:
    - torch==2.5.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
    - torchvision==0.20.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
    - gradio
