name: sam-batcher
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - matplotlib
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm
    - flask
    - requests
    - pycocotools>=2.0.8